### ISSUE TITLE
On long press left or right, it creates a clone of the gun component

### ISSUE THREAD

**Issue by AshishKapoor** [cinarrtolga/react-gun-fire-game#2]
<img width="1162" alt="Screenshot 2020-09-10 at 3 11 43 AM" src="https://user-images.githubusercontent.com/5203107/92658001-6f922b80-f313-11ea-8bcf-f04fb1fad95f.png">

**Comment by cinarrtolga** [comment]
Thank you for feedback. Clone problem fixed.
